branch-defaults:
  deploy:
    environment: faceclone-sqlite
    group_suffix: null
global:
  application_name: faceclone-v2
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
